apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webstore
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  workload_webstore: 'true'
              values:
                workload: webstore
          - git:
              repoURL: 'https://github.com/chauhangarima1808/eks-blueprints-workshop-gitops-apps'
              revision: 'HEAD'
              directories:
                - path: '{{values.workload}}/*'
  template:
    metadata:
      name: 'webstore-{{metadata.labels.environment}}-{{path.basename}}'
      labels:
        environment: '{{metadata.labels.environment}}'
        tenant: 'webstore'
        component: '{{path.basename}}'
        workloads: 'true'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/chauhangarima1808/eks-blueprints-workshop-gitops-apps'
        path: '{{path}}/{{metadata.labels.environment}}'
        targetRevision: 'HEAD'
      destination:
        namespace: '{{path.basename}}'
        name: '{{name}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
        retry:
          backoff:
            duration: 1m
            #limit: 100

